import os
import sys
import time
from string import Template

try:
    import simplejson as json
except ImportError:
    import json

from itertools import chain, combinations
from xml.etree.ElementTree import Element, SubElement, Comment, tostring, ElementTree
import config

# SITE_URL = ""


def paginator(posts, limit):
    limit = max(1, limit)
    return (posts[i:i+limit] for i in range(0, len(posts), limit))


def create_json():
    try:
        PDICT = []
        POSTS = sorted(os.scandir(config.POST_DIR),
                       key=lambda d: d.stat().st_mtime, reverse=True)
        ALLPOSTS = [post.name + "@" + time.strftime(
            "%Y-%m-%d", time.localtime(post.stat().st_mtime)) for post in POSTS]
        pagenum = 0
        for i in paginator(ALLPOSTS, config.PAGINATE_LIMIT):
            PDICT.append(i)
            pagenum += 1

        J = json.dumps(PDICT,  ensure_ascii=False, separators=(',', ':'))
        json.dump(J, open("o.json", "w"))
        return PDICT
    except Exception as e:
        print(e)
        return False


def generate_lastmod():
    P = sorted(os.scandir(config.POST_DIR),
               key=lambda d: d.stat().st_mtime, reverse=True)
    T = []
    for post in P:
        T.append(time.strftime("%Y-%m-%dT%H:%M:%S%z",
                               time.localtime(post.stat().st_mtime)))
    return T


def generate_sitemap(PDICT, TIMESTAMPS):
    try:
        top = Element("urlset")
        comment = Comment('Generated by Octopecto')
        top.append(comment)
        top.set("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
        top.set("xsi:schemaLocation",
                "http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd")
        top.set("xmlns", "http://www.sitemaps.org/schemas/sitemap/0.9")
        index = 0
        for item in PDICT[0]:
            x = SubElement(top, "url")
            loc = SubElement(
                x, "loc").text = f"{SITE_URL}/#/{item.split('@')[0]}"
            lastmod = SubElement(x, "lastmod").text = TIMESTAMPS[index]
            index += 1

        SM = ElementTree(top)
        SM.write("sitemap.xml", encoding="utf-8",
                 method="xml", xml_declaration=True)
        return True
    except Exception as e:
        print(e)
        return False


def generate_indexhtml():
    try:
        template = Template(open(config.INDEX_HTML_TEMPLATE, "r").read())

        about_template = f"""<p class="hitem about-link">
            <b><a href="{config.ABOUT_LINK}">ABOUT</a></b>
        </p>"""

        context = {"WEBSITE_NAME": config.WEBSITE_NAME,
                   "WEBSITE_DESCRIPTION": config.WEBSITE_DESCRIPTION,
                   "SITE_COVER": config.COVER_IMAGE,
                   "ABOUT_BLOCK": about_template if config.INCLUDE_ABOUT_LINK else "",
                   "AUTHOR": config.AUTHOR,
                   "AUTHOR_FACEBOOK": config.AUTHOR_FACEBOOK if config.AUTHOR_FACEBOOK else "",
                   "AUTHOR_TWITTER": config.AUTHOR_TWITTER if config.AUTHOR_TWITTER else "",
                   "SITE_URL": SITE_URL

                   }
        with open("index.html", "w") as ihtml:
            ihtml.write(template.safe_substitute(context))
        return True
    except Exception as e:
        print(e)
        return False


def main():

    print("OctoPecto Site Generation Started!")
    print("----------------------------------")
    start = time.perf_counter()
    print("Generating Index File! =>", end=" ")
    ihtml = generate_indexhtml()
    print("Success!" if ihtml else "Failed!")
    print("Generating Database JSON! =>", end=" ")
    posts = create_json()  # writes json database and returns the post list
    print("Success!" if posts else "Failed!")
    if config.GENERATE_SITEMAP:
        print("Generating Sitemap! =>", end=" ")
        # generates sitemap (experimental)
        sitemap = generate_sitemap(posts, generate_lastmod())
        print("Success!" if sitemap else "Failed!")
    print("Finished within {:.5f} seconds".format(time.perf_counter() - start))


if __name__ == "__main__":
    if len(sys.argv) == 2:
        if sys.argv[1] == "local":
            SITE_URL = ""
    else:
        SITE_URL = config.HOSTNAME + config.BASEPATH
    main()
